language: python
python:
  - "3.6"

env:
  - FLASK_APP="$TRAVIS_BUILD_DIR/autoapp.py"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - flask test